# Generated by Django 4.2.1 on 2023-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_id_alter_song_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='token',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='user_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
